{
 "title": "FX Orderbook Demo",
 "description": "FX Orderbook Demo with Arrays",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "750ms",
 "templating": {
  "list": [
   {
    "name": "SYMBOL",
    "label": "symbol",
    "query": "SELECT distinct SYMBOL FROM (\nSELECT  SYMBOL FROM core_price\nwhere timestamp > dateadd('d',-4,now())\nlatest on timestamp partition by symbol\n) order by symbol;\n"
   }
  ]
 },
 "panels": [
  { "title": "Last minute stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traded Volume last minute (all currencies)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as Time, Symbol, sum(bid_volume*bid_price) as Bid_Volume \nfrom core_price\nWHERE \n$__timeFilter(timestamp)\nSAMPLE BY 1y\nlimit 6\n--order by bid_volume desc \n--limit 10",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Spread and Volume per second - ${SYMBOL} ",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as Time, sum(asks[1,1]-bids[1,1]) as Spread, sum(bids[1,1]*bids[2,1]) as Bid_Volume, sum(asks[1,1]*asks[2,1]) as Ask_Volume\nfrom market_data\nWHERE \n$__timeFilter(timestamp) and symbol = '${SYMBOL}'\nSAMPLE BY 1s\norder by timestamp desc \nlimit 6",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Top-of-book Price vs Core Price - ${SYMBOL}",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "rawSql": "with p as (select timestamp, bid_price, bid_volume, symbol, ecn  from core_price where $__timeFilter(timestamp) and symbol = '${SYMBOL}' limit -6), levels as (\n        select market_data.timestamp as md_timestamp, insertion_point(bids[2], bid_volume) as level, bids[1][insertion_point(bids[2], bid_volume)] as price, bids[2][insertion_point(bids[2], bid_volume)] as volume, \n         p.timestamp, p.bid_price, p.bid_volume as bid_volume,p.ecn from p asof join market_data on symbol\n\n         )\n         select md_timestamp as MarketData_Time, case when price is null then null else level end as Level, Price, Volume, timestamp as CorePrice_Time, bid_price as Bid_Price, bid_volume1 as Bid_Volume, ecn as ECN from levels;",
     "selectedFormat": 1
    }
   ]
  },
  { "title": "OHLC Bars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "OHLC - Bids - 1m - (${SYMBOL})",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select timestamp, first(open) open, max(high) high, min(low) low, last(close) close, sum(total_volume) total_volume\n        from market_data_ohlc_1m\n        where  $__timeFilter(timestamp) and symbol = '${SYMBOL}'\n        sample by 2m\n        \n        \n"
    }
   ]
  },
  {
   "title": "OHLC - Bids - 15m - (${SYMBOL})",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 10, "x": 7, "y": 10 },
   "targets": [
    {
     "rawSql": "select timestamp, open, high, low,  close, total_volume\n        from market_data_ohlc_15m\n        where  $__timeFilter(timestamp) and symbol = '${SYMBOL}'\n        \n        \n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "OHLC - Bids - 1d - (${SYMBOL})",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "rawSql": "select timestamp, open, high, low,  close, total_volume\n        from market_data_ohlc_1d\n        where  $__timeFilter(timestamp) and symbol = '${SYMBOL}'\n        \n        \n",
     "selectedFormat": 2
    }
   ]
  },
  { "title": "VWAP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "VWAP today - 1m intervals - (${SYMBOL})",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "\nWITH sampled AS (\n    SELECT\n          timestamp,  symbol,\n          total_volume,\n          ((open+close)/2) * total_volume AS traded_value\n     FROM market_data_ohlc_1m\n     WHERE $__timeFilter(timestamp)\n      AND \n      symbol IN '${SYMBOL}'     \n), cumulative AS (\n     SELECT timestamp, symbol,\n           SUM(traded_value)\n                OVER (ORDER BY timestamp) AS cumulative_value,\n           SUM(total_volume)\n                OVER (ORDER BY timestamp) AS cumulative_volume\n     FROM sampled\n), vwap as (\nSELECT timestamp, cumulative_value/cumulative_volume AS vwap FROM cumulative\n), ohlc AS (\n     select timestamp, open, high, low,  close, total_volume\n        from market_data_ohlc_1m\n        where  $__timeFilter(timestamp) and symbol = '${SYMBOL}'\n)        \nselect * from vwap asof join ohlc        \n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "VWAP yesterday - 15m intervals - (${SYMBOL})",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "\nWITH sampled AS (\n    SELECT\n          timestamp,  symbol,\n          total_volume,\n          ((open+close)/2) * total_volume AS traded_value\n     FROM market_data_ohlc_15m\n     WHERE $__timeFilter(timestamp)\n      AND \n      symbol IN '${SYMBOL}'     \n), cumulative AS (\n     SELECT timestamp, symbol,\n           SUM(traded_value)\n                OVER (ORDER BY timestamp) AS cumulative_value,\n           SUM(total_volume)\n                OVER (ORDER BY timestamp) AS cumulative_volume\n     FROM sampled\n), vwap AS (\nSELECT timestamp, cumulative_value/cumulative_volume AS vwap FROM cumulative\n), ohlc AS (\nselect timestamp, open, high, low,  close, total_volume\n        from market_data_ohlc_15m\n        where  $__timeFilter(timestamp) and symbol = '${SYMBOL}'\n)\nselect * from vwap asof join ohlc        \n        \n",
     "selectedFormat": 2
    }
   ]
  },
  { "title": "Other Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Relative Strenght Index - 12h - (${SYMBOL})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH price_changes AS (\n    SELECT\n        timestamp,    \n        symbol,    \n        bid,\n        bid - prev_bid price_change\n    FROM (    \n      SELECT \n          timestamp,\n          symbol,\n          bid,\n          LAG(bid) OVER (PARTITION BY symbol ORDER BY timestamp) AS prev_bid\n      FROM bbo_1h\n      WHERE  $__timeFilter(timestamp)\n      AND symbol = '${SYMBOL}'\n    )  \n),\ngains_losses AS (\n    SELECT \n        timestamp,\n        symbol,\n        bid,\n        CASE WHEN price_change > 0 THEN price_change ELSE 0 END AS gain,\n        CASE WHEN price_change < 0 THEN ABS(price_change) ELSE 0 END AS loss\n    FROM price_changes\n),\n\navg_gains_losses AS (\n    SELECT \n        timestamp,\n        symbol,\n        bid,\n        AVG(gain) OVER (PARTITION BY symbol ORDER BY timestamp ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS avg_gain,\n        AVG(loss) OVER (PARTITION BY symbol ORDER BY timestamp ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS avg_loss\n    FROM gains_losses\n)\n\nSELECT \n    timestamp,    \n    Bid,\n    CASE \n        WHEN avg_loss = 0 THEN 100\n        ELSE 100 - (100 / (1 + (avg_gain / NULLIF(avg_loss, 0))))\n    END AS RSI_12h\nFROM avg_gains_losses\nORDER BY timestamp;\n"
    }
   ]
  },
  {
   "title": "Bollinger Bands (20, 2) – 15m OHLC (6h Window) - (${SYMBOL})",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH stats AS (\n  SELECT\n    timestamp,\n    close,\n    AVG(close) OVER (\n      ORDER BY timestamp\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\n    ) AS sma20,\n    AVG(close * close ) OVER (\n      ORDER BY timestamp\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW \n    ) AS avg_close_sq\n  FROM market_data_ohlc_15m -- 20 periods of 15 minutes = SMA 6h\n   WHERE  $__timeFilter(timestamp)\n      AND symbol IN '${SYMBOL}'\n), bollinger AS (\nSELECT\n  timestamp,\n  sma20,\n  -- sqrt(avg_close_sq - (sma20 * sma20)) as stdev20,\n  sma20 + 2 * sqrt(avg_close_sq - (sma20 * sma20)) as upper_band,\n  sma20 - 2 * sqrt(avg_close_sq - (sma20 * sma20)) as lower_band\nFROM stats\nORDER BY timestamp ),\nohlc as (\n  select timestamp, open, high, low,  close, total_volume\n        from market_data_ohlc_15m\n        where  $__timeFilter(timestamp) and symbol = '${SYMBOL}'\n)\nselect * from bollinger asof join ohlc"
    }
   ]
  },
  { "title": "Bids / Asks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Bid vs Ask Volume -  30s - (${SYMBOL})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "\nSELECT timestamp time, symbol, sum(bids[1,1] * bids[2,1]) as bid, -1 * sum(asks[1,1] * asks[2,1]) as ask\n  from market_data where $__timeFilter(timestamp) and \nsymbol IN '${SYMBOL}'\nsample by 30s;\n\n\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Best Bid and Offer - 1s - (${SYMBOL})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "rawSql": "--SELECT timestamp as time,  symbol,\n--avg(bid) best_bid,\n--avg(ask) best_ask,\n--avg((bid+ask)/2) best_mid,\n-- FROM \"bbo_1s\" \n--WHERE $__timeFilter(timestamp)\n--and symbol IN '${SYMBOL}'\n--SAMPLE BY $__sampleByInterval\n\nSELECT timestamp as Time,  Symbol, Bid, Ask, (bid+ask)/2 as Mid\n FROM \"bbo_1s\" \nWHERE $__timeFilter(timestamp)\nand symbol IN '${SYMBOL}'\n",
     "selectedFormat": 2
    }
   ]
  }
 ]
}